### ISSUE TITLE
Employee Management

### ISSUE THREAD

**Issue by enginbulut** [enginbulut/hrcebimde#2]
- All crud operations
- Link with users
- Link with titles
- Link with branches
- Link with departments

**Comment by enginbulut** [comment]
Employee Management
- we should list all users who have guest role and don't have any employee record
- An employee must be related to a user
- An employee must be related to a branch
- An employee must be related to a department
- And also an employee must have the fields that already written in the form.
- Also, we need a route for getting employee details by user id.
- For last, we need a route for upserting employee records.

**Comment by whisper3d** [comment]
> Employee Management
> 
> * we should list all users who have guest role and don't have any employee record
> * An employee must be related to a user
> * An employee must be related to a branch
> * An employee must be related to a department
> * And also an employee must have the fields that already written in the form.
> * Also, we need a route for getting employee details by user id.
> * For last, we need a route for upserting employee records.

**Comment by whisper3d** [comment]
> Employee Management
> 
> * we should list all users who have guest role and don't have any employee record
> * An employee must be related to a user
> * An employee must be related to a branch
> * An employee must be related to a department
> * And also an employee must have the fields that already written in the form.
> * Also, we need a route for getting employee details by user id.
> * For last, we need a route for upserting employee records.

an employee must be a user requirement changed. some employees will not have email address so they have to be created without a user. if an employee needs to be connected with a user manager or above should be able to make relation via app.

**Comment by whisper3d** [comment]
user changed to required in the employee schema
